name: PR/Push Checks

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build Extension Source
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "12"

      - name: Setup Dependencies
        run: npm ci

      - name: Build Extension
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-extension
          path: dist

  code-formatting:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "12"

      - name: Setup Dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run prettier

      - name: Run ESLint
        run: npm run eslint
