name: Publish Docs

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-18.04
    steps:
      - name: Download compiled docs Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: compiled-docs

      - name: Display artifact files
        run: ls -l

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: .
